create table produto (
    id              bigint generated by default as identity primary key,
    codigo          varchar(20)    not null unique,
    descricao       varchar(120)   not null,
    ncm             varchar(8)     not null,
    cfop            varchar(4)     not null,
    unidade         varchar(6)     not null,
    valor_unitario  numeric(15, 2) not null
);

create table cliente (
    id         bigint generated by default as identity primary key,
    documento  varchar(14)  not null unique,
    nome       varchar(120) not null,
    uf         varchar(2)   not null,
    email      varchar(120)
);

-- Numeração da nota gerada pelo banco: atômica, sem condição de corrida entre instâncias
create sequence nota_numero_seq;

create table nota_fiscal (
    id             bigint generated by default as identity primary key,
    numero         bigint         not null,
    serie          integer        not null,
    chave_acesso   varchar(44)    not null unique,
    status         varchar(20)    not null,
    cliente_id     bigint         not null references cliente (id),
    valor_total    numeric(15, 2) not null,
    data_emissao   timestamp(6) with time zone not null,
    protocolo      varchar(20),
    motivo         varchar(255),
    xml            text,
    constraint uk_nota_serie_numero unique (serie, numero)
);

create index idx_nota_status on nota_fiscal (status);

create table item_nota (
    id              bigint generated by default as identity primary key,
    nota_id         bigint         not null references nota_fiscal (id) on delete cascade,
    produto_id      bigint         not null references produto (id),
    quantidade      numeric(15, 4) not null,
    valor_unitario  numeric(15, 2) not null,
    valor_total     numeric(15, 2) not null
);

create index idx_item_nota_nota on item_nota (nota_id);
