create table evento_outbox (
    id            bigint generated by default as identity primary key,
    tipo          varchar(60)  not null,
    chave         varchar(100) not null,
    payload       text         not null,
    criado_em     timestamp(6) with time zone not null,
    publicado_em  timestamp(6) with time zone
);

create index idx_outbox_pendentes on evento_outbox (id) where publicado_em is null;

create table auditoria_nfe (
    id              bigint generated by default as identity primary key,
    chave_acesso    varchar(44)    not null unique,
    numero          bigint         not null,
    protocolo       varchar(20)    not null,
    cliente_nome    varchar(120)   not null,
    valor_total     numeric(15, 2) not null,
    autorizada_em   timestamp(6) with time zone not null,
    registrada_em   timestamp(6) with time zone not null,
    particao        integer        not null,
    offset_kafka    bigint         not null
);
