services:
  postgres:
    image: postgres:17
    container_name: nfe-postgres
    environment:
      POSTGRES_DB: nfe
      POSTGRES_USER: nfe
      POSTGRES_PASSWORD: nfe
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  sefaz:
    build: ./sefaz-mock
    container_name: nfe-sefaz
    ports:
      - "8180:8080"
      - "9991:9990"

  infinispan:
    image: quay.io/infinispan/server:latest
    container_name: nfe-infinispan
    environment:
      USER: admin
      PASS: admin
    ports:
      - "11222:11222"

  kafka:
    image: apache/kafka:latest
    container_name: nfe-kafka
    ports:
      - "9092:9092"

  kafka-topicos:
    image: apache/kafka:latest
    container_name: nfe-kafka-topicos
    network_mode: "service:kafka"
    depends_on:
      - kafka
    entrypoint: ["/bin/bash", "-c"]
    command:
      - |
        until /opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list > /dev/null 2>&1; do sleep 1; done
        /opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --create --if-not-exists --topic nfe-autorizada --partitions 3 --replication-factor 1
        /opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --describe --topic nfe-autorizada

volumes:
  pgdata:
