quarkus.http.port=8081
quarkus.http.test-port=0

quarkus.datasource.db-kind=postgresql
%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5433/nfe
%prod.quarkus.datasource.jdbc.url=${DB_URL:jdbc:postgresql://localhost:5433/nfe}
%dev.quarkus.datasource.username=nfe
%dev.quarkus.datasource.password=nfe
%prod.quarkus.datasource.username=${DB_USER:nfe}
%prod.quarkus.datasource.password=${DB_PASSWORD:nfe}

quarkus.flyway.migrate-at-start=true
quarkus.hibernate-orm.schema-management.strategy=validate
%dev.quarkus.hibernate-orm.log.sql=true

nfe.emitente.cnpj=11222333000181
nfe.emitente.razao-social=Loja Estudo LTDA
nfe.emitente.uf=SP
nfe.emitente.codigo-uf=35
nfe.emitente.serie=1

quarkus.smallrye-openapi.info-title=NF-e Estudo API
quarkus.swagger-ui.always-include=true

quarkus.cxf.codegen.wsdl2java.includes=wsdl/NFeAutorizacao.wsdl
quarkus.cxf.codegen.wsdl2java.package-names=br.estudo.nfe.sefaz.ws
quarkus.cxf.client.sefaz.service-interface=br.estudo.nfe.sefaz.ws.NFeAutorizacao
quarkus.cxf.client.sefaz.client-endpoint-url=${SEFAZ_URL:http://localhost:8180/sefaz-mock/NFeAutorizacao}
quarkus.cxf.client.sefaz.connection-timeout=2000
quarkus.cxf.client.sefaz.receive-timeout=5000

nfe.sefaz.intervalo-consulta=5s
%test.quarkus.scheduler.enabled=false

%dev.kafka.bootstrap.servers=localhost:9092
%prod.kafka.bootstrap.servers=${KAFKA_BOOTSTRAP:localhost:9092}
quarkus.kafka.devservices.topic-partitions.nfe-autorizada=3

mp.messaging.outgoing.nfe-autorizada.connector=smallrye-kafka
mp.messaging.outgoing.nfe-autorizada.topic=nfe-autorizada
mp.messaging.outgoing.nfe-autorizada.acks=all
mp.messaging.outgoing.nfe-autorizada.enable.idempotence=true
mp.messaging.outgoing.nfe-autorizada.max.block.ms=3000
mp.messaging.outgoing.nfe-autorizada.request.timeout.ms=3000
mp.messaging.outgoing.nfe-autorizada.delivery.timeout.ms=6000

mp.messaging.incoming.auditoria-nfe.connector=smallrye-kafka
mp.messaging.incoming.auditoria-nfe.topic=nfe-autorizada
mp.messaging.incoming.auditoria-nfe.group.id=auditoria
mp.messaging.incoming.auditoria-nfe.auto.offset.reset=earliest
mp.messaging.incoming.auditoria-nfe.failure-strategy=dead-letter-queue

nfe.outbox.intervalo=2s
